// 32bit colors (0xRRGGBBAA) // alpha is always 0xFF as transparency can only be used via textures in the RDP

constant COLOR_RED(0xFF0000FF)

constant COLOR_GREEN(0x00FF00FF)
constant COLOR_DARKGREEN(0x008800FF)

constant COLOR_BLUE(0x0000FFFF)
constant COLOR_CYAN(0x00FFFFFF)

constant COLOR_BLACK(0x000000FF)
constant COLOR_WHITE(0xFFFFFFFF)

constant COLOR_LIGHTGREY(0xC0C0C0FF)
constant COLOR_GREY(0x808080FF)
constant COLOR_DARKGREY(0x404040FF)

